(function(root){
'use strict';
const cents=n=>Math.round(Number(n)*100),uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,9);
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
function num(n,label,integer=false){n=Number(n);if(!Number.isFinite(n)||n<0||(integer&&!Number.isInteger(n)))throw Error(label+': valor inválido.');return n;}
function empty(){return {version:2,products:[],clients:[],sales:[],expenses:[],links:[],leads:[],settings:{name:'NFC PRO',city:'Ibiporã, Paraná',theme:'light',endpoint:'/api/places'}};}
function stock(d,id){return (d.products.find(p=>p.id===id)?.quantity||0)-d.sales.filter(s=>s.productId===id&&s.status!=='Cancelado').reduce((n,s)=>n+s.quantity,0);}
function sale(d,v,id){const p=d.products.find(p=>p.id===v.productId),c=d.clients.find(c=>c.id===v.clientId),old=d.sales.find(s=>s.id===id);if(!p||!c)throw Error('Selecione o modelo e o cliente.');const quantity=num(v.quantity,'Quantidade',true),unitPrice=num(v.unitPrice,'Preço'),discount=num(v.discount,'Desconto');if(!quantity)throw Error('A quantidade deve ser maior que zero.');if(cents(discount)>cents(unitPrice)*quantity)throw Error('Desconto maior que a venda.');const status=['Pago','Pendente','Cancelado'].includes(v.status)?v.status:'Pendente';const available=stock(d,p.id)+(old?.productId===p.id&&old.status!=='Cancelado'?old.quantity:0);if(status!=='Cancelado'&&quantity>available)throw Error(`Estoque insuficiente. Disponível: ${available}.`);if(!/^\d{4}-\d{2}-\d{2}$/.test(v.date))throw Error('Informe a data.');return {id:id||uid(),productId:p.id,productName:p.name,clientId:c.id,clientName:c.name,city:c.city,quantity,unitPrice,discount,total:(cents(unitPrice)*quantity-cents(discount))/100,cost:old?.productId===p.id?old.cost:p.cost,status,date:v.date,payment:v.payment||'Pix',delivered:!!v.delivered,notes:String(v.notes||'').slice(0,2000)};}
function metrics(d,rows=d.sales,ex=d.expenses){const valid=rows.filter(s=>s.status!=='Cancelado'),paid=valid.filter(s=>s.status==='Pago');const sum=(r,f)=>r.reduce((n,x)=>n+cents(f(x)),0)/100;const revenue=sum(paid,s=>s.total),pending=sum(valid.filter(s=>s.status==='Pendente'),s=>s.total),cogs=sum(paid,s=>s.cost*s.quantity),operating=sum(ex,e=>e.amount),purchased=sum(d.products,p=>p.cost*p.quantity);return {revenue,pending,cogs,operating,profit:(cents(revenue)-cents(cogs)-cents(operating))/100,invested:purchased+sum(d.expenses,e=>e.amount),stock:d.products.reduce((n,p)=>n+stock(d,p.id),0),sold:valid.reduce((n,s)=>n+s.quantity,0),margin:revenue?(revenue-cogs-operating)/revenue*100:0};}
function http(value){let u;try{u=new URL(value);}catch{throw Error('Informe um endereço completo com https://.');}if(!['https:','http:'].includes(u.protocol)||u.username||u.password)throw Error('Endereço inválido.');return u.href;}
function link(type,value,message=''){value=value.trim();if(!value)throw Error('Preencha o campo.');if(type==='instagram'){if(/^https?:\/\//i.test(value)){const u=new URL(http(value));if(!['www.instagram.com','instagram.com'].includes(u.hostname))throw Error('Use um perfil do Instagram.');value=u.pathname.replace(/^\/+|\/+$/g,'');}value=value.replace(/^@/,'');if(!/^[a-zA-Z0-9._]{1,30}$/.test(value))throw Error('Usuário do Instagram inválido.');return `https://www.instagram.com/${value}/`;}if(type==='whatsapp'){const n=value.replace(/\D/g,'');if(!/^[1-9]\d{9,14}$/.test(n))throw Error('Informe país, DDD e telefone. Ex.: 5543999999999.');return `https://wa.me/${n}${message?'?text='+encodeURIComponent(message):''}`;}if(type==='google'){if(/^[A-Za-z0-9_-]{10,300}$/.test(value))return 'https://search.google.com/local/writereview?placeid='+encodeURIComponent(value);const u=new URL(http(value));if(u.hostname==='g.page'&&/\/review\/?$/.test(u.pathname))return u.href;if(/^(www\.|search\.)?google\.(com|com\.br)$/.test(u.hostname)&&(u.pathname.includes('writereview')||/!9m1!1b1/.test(u.href)))return u.href;throw Error('Use o Place ID ou um link direto de avaliação. Links comuns do Maps não são suficientes.');}if(type==='group'){const u=new URL(http(value));if(u.hostname!=='chat.whatsapp.com'||u.pathname.length<8)throw Error('Use o convite do grupo WhatsApp.');return u.href;}return http(value);}
function leads(rows,f){return rows.filter(r=>(r.rating||0)>=Number(f.rating||0)&&(r.reviews||0)>=Number(f.reviews||0)&&(!f.phone||r.phone)&&(!f.website||r.website)&&(!f.open||r.open===true)&&(!f.status||r.status===f.status)).sort((a,b)=>f.sort==='rating'?(b.rating||0)-(a.rating||0):f.sort==='name'?a.name.localeCompare(b.name):(b.reviews||0)-(a.reviews||0));}
function validate(d){if(!d||d.version!==2||!d.settings)throw Error('Backup incompatível.');for(const key of ['products','clients','sales','expenses','links','leads']){if(!Array.isArray(d[key])||d[key].length>20000)throw Error('Backup inválido: '+key);const ids=new Set();for(const r of d[key]){if(!r||typeof r.id!=='string'||ids.has(r.id))throw Error('IDs inválidos.');ids.add(r.id);}}for(const p of d.products){if(typeof p.name!=='string'||!p.name.trim())throw Error('Modelo inválido.');num(p.quantity,'Quantidade',true);num(p.cost,'Custo');num(p.price,'Preço');if(p.image&&!/^data:image\/(jpeg|png|webp);base64,/.test(p.image))throw Error('Imagem inválida.');}for(const c of d.clients)if(typeof c.name!=='string'||!c.name.trim())throw Error('Cliente inválido.');for(const s of d.sales){if(!d.products.some(p=>p.id===s.productId)||!d.clients.some(c=>c.id===s.clientId))throw Error('Venda sem modelo ou cliente.');num(s.quantity,'Quantidade',true);num(s.total,'Total');num(s.cost,'Custo');num(s.unitPrice,'Preço');num(s.discount,'Desconto');if(!s.quantity||!['Pago','Pendente','Cancelado'].includes(s.status)||!/^\d{4}-\d{2}-\d{2}$/.test(s.date)||cents(s.total)!==cents(s.unitPrice)*s.quantity-cents(s.discount))throw Error('Venda inválida.');}for(const p of d.products)if(stock(d,p.id)<0)throw Error('Estoque negativo.');for(const e of d.expenses){num(e.amount,'Despesa');if(!/^\d{4}-\d{2}-\d{2}$/.test(e.date))throw Error('Data inválida.');}for(const l of d.links){http(l.url);if(typeof l.name!=='string')throw Error('Link inválido.');}for(const l of d.leads)if(typeof l.name!=='string')throw Error('Comércio inválido.');return d;}
const api={cents,uid,today,num,empty,stock,sale,metrics,http,link,leads,validate};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.NFC=api;
})(typeof window!=='undefined'?window:globalThis);
