const test=require('node:test'),assert=require('node:assert/strict'),N=require('../core.js');
function fixture(){const d=N.empty();d.products.push({id:'p',name:'Google Azul',quantity:10,cost:8,price:80});d.clients.push({id:'c',name:'Cliente teste',city:'Ibiporã'});return d;}
const values={productId:'p',clientId:'c',quantity:2,unitPrice:80,discount:10,date:'2026-09-27',status:'Pago'};
test('venda desconta estoque e calcula total e lucro sem duplicar investimento',()=>{const d=fixture();d.sales.push(N.sale(d,values));d.expenses.push({id:'e',name:'Transporte',amount:5,date:'2026-09-27'});assert.equal(N.stock(d,'p'),8);const m=N.metrics(d);assert.equal(m.revenue,150);assert.equal(m.cogs,16);assert.equal(m.profit,129);assert.equal(m.invested,85);N.validate(d);});
test('cancelamento devolve estoque; pendente reserva estoque sem gerar lucro',()=>{const d=fixture();const s=N.sale(d,{...values,status:'Pendente'});d.sales.push(s);assert.equal(N.metrics(d).pending,150);assert.equal(N.metrics(d).revenue,0);d.sales[0]=N.sale(d,{...values,status:'Cancelado'},s.id);assert.equal(N.stock(d,'p'),10);assert.equal(N.metrics(d).pending,0);});
test('edicao nao desconta duas vezes; custo da venda fica congelado',()=>{const d=fixture(),s=N.sale(d,values);d.sales.push(s);d.products[0].cost=20;d.sales[0]=N.sale(d,{...values,quantity:3},s.id);assert.equal(N.stock(d,'p'),7);assert.equal(d.sales[0].cost,8);assert.throws(()=>N.sale(d,{...values,quantity:8}),/Estoque/);});
test('valida dinheiro, quantidade e desconto',()=>{const d=fixture();for(const bad of [{quantity:-1},{quantity:1.5},{quantity:0},{unitPrice:NaN},{discount:999}])assert.throws(()=>N.sale(d,{...values,...bad}));assert.equal(N.sale(d,{...values,quantity:3,unitPrice:.1,discount:0}).total,.3);});
test('links corretos e rejeicao de esquemas perigosos e Maps comuns',()=>{assert.equal(N.link('instagram','@reuse'),'https://www.instagram.com/reuse/');assert.match(N.link('whatsapp','+55 (43) 99999-9999','Olá!'),/^https:\/\/wa.me\/5543999999999\?text=Ol/);assert.match(N.link('google','ChIJ1234567890'),/writereview\?placeid=ChIJ/);assert.throws(()=>N.link('site','javascript:alert(1)'));assert.throws(()=>N.link('google','https://maps.app.goo.gl/abc'));assert.throws(()=>N.link('instagram','https://evil.test/user'));});
test('filtros de leads e ordenacao',()=>{const rows=[{name:'A',rating:4.8,reviews:10,phone:'123',open:true},{name:'B',rating:4.1,reviews:200},{name:'C',rating:4.9,reviews:30,phone:'321',open:true}];assert.deepEqual(N.leads(rows,{rating:4.5,phone:true,sort:'reviews'}).map(r=>r.name),['C','A']);});
test('backup rejeita referencias quebradas e imagens ativas',()=>{const d=fixture();d.sales.push(N.sale(d,values));const backup=JSON.parse(JSON.stringify(d));N.validate(backup);backup.products[0].image='data:image/svg+xml,<svg/>';assert.throws(()=>N.validate(backup));delete backup.products[0].image;backup.clients=[];assert.throws(()=>N.validate(backup));});
test('Google adapter envia apenas campos e parametros esperados',async()=>{const {searchPlaces}=await import('../integration/places.mjs');let sent;const result=await searchPlaces({query:'Academia',city:'Ibiporã',minRating:4},'test-key',async(url,opts)=>{sent={url,...opts};return {ok:true,json:async()=>({places:[{id:'x'}]})};});assert.equal(result.places[0].id,'x');assert.equal(JSON.parse(sent.body).textQuery,'Academia em Ibiporã');assert.match(sent.headers['X-Goog-FieldMask'],/googleMapsLinks/);await assert.rejects(()=>searchPlaces({query:'',city:'x'},'key'));});
